---
# hdblcm prepare

# Create directory {{ sap_hana_install_software_extract_directory }}
# This is where all extracted .SAR files will be stored

- name: SAP HANA hdblcm prepare - Remove directory '{{ sap_hana_install_software_extract_directory }}'
  file:
    path: "{{ sap_hana_install_software_extract_directory }}"
    state: absent
  tags:
    - sap_hana_install_prepare_sapcar
    - sap_hana_install_prepare_sarfiles

- name: SAP HANA hdblcm prepare - Create directory '{{ sap_hana_install_software_extract_directory }}'
  file:
    path: "{{ sap_hana_install_software_extract_directory }}"
    state: directory
    mode: '0755'
  tags:
    - sap_hana_install_prepare_sapcar
    - sap_hana_install_prepare_sarfiles

- name: SAP HANA hdblcm prepare - Create SAPCAR directory '{{ sap_hana_install_software_extract_directory }}/sapcar'
  file:
    path: "{{ sap_hana_install_software_extract_directory }}/sapcar"
    state: directory
    mode: '0755'
  tags:
    - sap_hana_install_prepare_sapcar
    - sap_hana_install_prepare_sarfiles

- name: SAP HANA hdblcm prepare - Create status file '{{ sap_hana_install_software_extract_directory }}/__EXTRACTION_ONGOING__'
  file:
    path: "{{ sap_hana_install_software_extract_directory }}/__EXTRACTION_ONGOING__"
    state: touch
    mode: '0755'

- name: SAP HANA hdblcm prepare - Prepare SAPCAR
  import_tasks: prepare_sapcar.yml
  tags:
    - sap_hana_install_prepare_sapcar
    - sap_hana_install_prepare_sarfiles

- name: SAP HANA hdblcm prepare - Prepare SAR files
  import_tasks: prepare_sarfiles.yml
  tags: sap_hana_install_prepare_sarfiles

- name: SAP HANA hdblcm prepare - Remove status file '{{ sap_hana_install_software_extract_directory }}/__EXTRACTION_ONGOING__'
  file:
    path: "{{ sap_hana_install_software_extract_directory }}/__EXTRACTION_ONGOING__"
    state: absent

- name: SAP HANA hdblcm prepare - Find 'SAP_HANA_DATABASE' in '{{ sap_hana_install_software_extract_directory }}'
  find:
    paths: "{{ sap_hana_install_software_extract_directory }}"
    recurse: yes
    file_type: directory
    patterns: 'SAP_HANA_DATABASE'
  register: __sap_hana_install_register_find_directory_sap_hana_database

- name: SAP HANA hdblcm prepare - Set fact for 'hdblcm' installer path
  set_fact:
    __sap_hana_install_fact_hdblcm_path:
      "{{ __sap_hana_install_register_find_directory_sap_hana_database.files[0].path }}"
  when: not ansible_check_mode
