---

- name: Rename some variables used by hdblcm configfile
  set_fact:
    sap_hana_install_sid: "{{ sap_hana_sid|d(sap_hana_install_sid)|d('') }}"
    sap_hana_install_number: "{{ sap_hana_instance_number|d(sap_hana_install_instance_number|d(sap_hana_install_number)|d('')) }}"
    sap_hana_install_master_password: "{{ sap_hana_install_common_master_password|d(sap_hana_install_master_password) }}"
    sap_hana_install_system_usage: "{{ sap_hana_install_env_type|d(sap_hana_install_system_usage) }}"
    sap_hana_install_restrict_max_mem: "{{ sap_hana_install_mem_restrict|d(sap_hana_install_restrict_max_mem) }}"
  tags:
    - sap_hana_install_preinstall
    - sap_hana_install_set_log_mode
    - sap_hana_install_configure_firewall
    
- debug:
    msg: "{{ sap_hana_install_sid }}"

- name: Fail if necessary variable 'sap_hana_install_sid' is not configured
  fail:
    msg: "Variable 'sap_hana_install_sid' is not configured."
  when: sap_hana_install_sid | length == 0
  tags: sap_hana_install_preinstall

- name: Fail if necessary variable 'sap_hana_install_number' is not configured
  fail:
    msg: "Variable 'sap_hana_install_number' is not configured."
  when: sap_hana_install_number | length == 0
  tags: sap_hana_install_preinstall

- name: SAP HANA existence checking
  #ansible.builtin.import_tasks: hana_exists.yml
  import_tasks: hana_exists.yml
  when: sap_hana_install_new_system|d(true)

- name: SAP HANA pre-install steps
  import_tasks: pre_install.yml
  tags: sap_hana_install_preinstall

- name: SAP HANA installation steps
  import_tasks: hana_install.yml
  when: sap_hana_install_new_system|d(true)

- name: SAP HANA addhosts steps
  import_tasks: hana_addhosts.yml
  when: not sap_hana_install_new_system|d(true)

- name: SAP HANA post-install steps
  import_tasks: post_install.yml
